[FIX] Start updating redcap record event IDs
TIGRLab/datman-dashboard pull request #89
Opened 2022-02-12 02:18 UTC by DESm1th

@josephmje noticed that the event IDs werent being set on redcap records in the database when the dashboard created them. This pull request addresses this issue.

- Add a column on RedcapConfig to store the event name -> event ID mappings 98c0d5179a6896c9789cc968cedfe88555d14278
- Add a migration script to update the database 7a11d629efe86004dfd1974226c3b3b7b1a42649
- Allow parse_config.py to update the event_ids column from the config files 01c97aef1f44ac21de2894a7bc76bd71f24b144c
- Add tests for `dashboard.blueprints.redcap.utils.create_from_request` to describe correct behavior for the function 912556cf6c44ee125df59364ad734670a2411bd6, b6b0641329ac857b573073fa3b06232b06e3e1f3, 8b08ae0a977e78bf4349b9e820d14e3427ec23e8
- Push the event ID for the received event name with the rest of the redcap record update 8b74be5c1a22e7a517a30b59ea9f4256bbd21cf2
-  Fix an unrelated bug where redcap version updates were causing "can't set attribute" errors a314acbd84fb34b71b3b196cc8d7ed0685a560ac
- Fix an unrelated bug where the redcap version wasn't being updated when data entry triggers were sent 9523ef5e5f2adcab4150f08ce8e66ecaf5cf9249
- Fix an exception caused when RedcapConfig doesnt have event_ids defined d063fa0cbb26e3e342460fc822c2cacdf13f0412

2022-03-01 15:15 UTC, jerdra requested changes

2022-03-01 15:15 UTC, jerdra commented on tests/test_redcap_bp_utils.py
> +        assert not rc.event_ids
```suggestion
        assert rc.event_ids is None
```

Would making this more explicit work ok? Or will `rc.event_ids` not return a null type if unset

2022-03-01 17:23 UTC, DESm1th commented
Thanks for the feedback Jer! I made the changes

2022-03-02 01:10 UTC, jerdra approved these changes
Thanks Dawn!

2022-03-02 17:03 UTC, josephmje approved these changes

2022-03-02 20:47 UTC, merged